services:
  - type: web
    name: highflow-verify-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    autoDeploy: true
    envVars:
      - key: DISCORD_BOT_TOKEN
        sync: false
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: REDIRECT_URI
        sync: false
      - key: GUILD_ID
        sync: false
      - key: VERIFIED_ROLE_ID
        sync: false
      - key: PORT
        value: 10000
